fix missing include <strings.h> for index() (fixes #33791)
tests/basic_tests.c:2141:7: warning: implicit declaration of function 'index' [-Wimplicit-function-declaration]
  qs = index(authnRequestUrl, '?') + 1;
       ^~~~~
tests/basic_tests.c:2141:7: warning: incompatible implicit declaration of built-in function 'index'